### ISSUE TITLE
cargo run failed 

### ISSUE THREAD

**Issue by weiforce** [rbatis/abs_admin#11]
error: custom attribute panicked
 --> src/domain/mapper/sys_dict.rs:2:1
  |
2 | crud!(SysDict {});
  | ^^^^^^^^^^^^^^^^^
  |
  = help: message: [rbatis] parse py_sql fail!: E("[rbatis] express trim value must be string value, for example:  trim 'value',error express: \\',\\'")
  = note: this error originates in the macro `$crate::impl_insert` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0425]: cannot find function `delete_by_column_batch` in this scope
 --> src/domain/mapper/sys_user_role.rs:2:1
  |
2 | crud!(SysUserRole {});
  | ^^^^^^^^^^^^^^^^^^^^^ not found in this scope
  |
  = note: this error originates in the macro `$crate::impl_delete` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0425]: cannot find function `select_list_in_user_id` in this scope
 --> src/domain/mapper/sys_user_role.rs:3:26
  |
3 | impl_select!(SysUserRole{select_list_in_user_id(user_ids:&[String])=>
  |                          ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0425, E0762.
For more information about an error, try `rustc --explain E0425`.

**Comment by lmmqxyx404** [comment]
Perhaps your dependency version of rbatis is wrong.
Once verify your depencency version. Have a try with deleting relattive "target" directory.

**Comment by zhuxiujia** [comment]
run `git pull`
run `cargo update`
run `cargo run`
