### ISSUE TITLE
缓存设置用mem时不起作用，无法写入数据

### ISSUE THREAD

**Issue by sunkaifei** [rbatis/abs_admin#23]
如题，插入不了数据，获取不到插入的数据
<img width="701" alt="082115e955c0edda6ec2867a188a193" src="https://github.com/rbatis/abs_admin/assets/20941411/898da843-0ad3-4349-b055-a7f6e1498dff">

**Comment by zhuxiujia** [comment]
git pull 拉取更新代码在试试

**Comment by sunkaifei** [comment]
![image](https://github.com/rbatis/abs_admin/assets/20941411/11ecc618-d3d9-45ba-9f46-a93846871773)
还是没有写入缓存
