### ISSUE TITLE
cargo run报error[E0659]

### ISSUE THREAD

**Issue by richardgong1987** [rbatis/abs_admin#8]
### 系统环境:

mac系统最新版本,

Rust最新版本.

报错如下:

```
error[E0659]: `parse_quote_spanned` is ambiguous
   --> /Users/richard/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/pin-project-internal-0.4.28/src/pin_project/derive.rs:865:67
    |
865 |                 proj_generics.make_where_clause().predicates.push(parse_quote_spanned! { span =>
    |                                                                   ^^^^^^^^^^^^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of a conflict between a `macro_rules` name and a non-`macro_rules` name from another module
note: `parse_quote_spanned` could refer to the macro defined here
   --> /Users/richard/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/pin-project-internal-0.4.28/src/utils.rs:23:1
    |
23  | / macro_rules! parse_quote_spanned {
24  | |     ($span:expr => $($tt:tt)*) => {
25  | |         syn::parse2(quote::quote_spanned!($span => $($tt)*)).unwrap_or_else(|e| panic!("{}", e))
26  | |     };
27  | | }
    | |_^
note: `parse_quote_spanned` could also refer to the macro imported here
   --> /Users/richard/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/pin-project-internal-0.4.28/src/pin_project/derive.rs:7:5
    |
7   |     *,
    |     ^
    = help: use `self::parse_quote_spanned` to refer to this macro unambiguously

error[E0659]: `parse_quote_spanned` is ambiguous
   --> /Users/richard/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/pin-project-internal-0.4.28/src/pinned_drop.rs:108:21
    |
108 |             *path = parse_quote_spanned! { path.span() =>
    |                     ^^^^^^^^^^^^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of a conflict between a `macro_rules` name and a non-`macro_rules` name from another module
note: `parse_quote_spanned` could refer to the macro defined here
   --> /Users/richard/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/pin-project-internal-0.4.28/src/utils.rs:23:1
    |
23  | / macro_rules! parse_quote_spanned {
24  | |     ($span:expr => $($tt:tt)*) => {
25  | |         syn::parse2(quote::quote_spanned!($span => $($tt)*)).unwrap_or_else(|e| panic!("{}", e))
26  | |     };
27  | | }
    | |_^
note: `parse_quote_spanned` could also refer to the macro imported here
   --> /Users/richard/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/pin-project-internal-0.4.28/src/pinned_drop.rs:3:50
    |
3   | use syn::{spanned::Spanned, visit_mut::VisitMut, *};
    |                                                  ^
    = help: use `self::parse_quote_spanned` to refer to this macro unambiguously

For more information about this error, try `rustc --explain E0659`.
error: could not compile `pin-project-internal` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by richardgong1987** [comment]
@zhuxiujia 

@eumji025

**Comment by peanut-cc** [comment]
> @zhuxiujia
> 
> @eumji025

应该还是你本地环境的问题吧，我今天刚尝试和运行是正常的

**Comment by zhuxiujia** [comment]
> ### 系统环境:
> mac系统最新版本,
> 
> Rust最新版本.
> 
> 报错如下:
> 
> ```
> error[E0659]: `parse_quote_spanned` is ambiguous
>    --> /Users/richard/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/pin-project-internal-0.4.28/src/pin_project/derive.rs:865:67
>     |
> 865 |                 proj_generics.make_where_clause().predicates.push(parse_quote_spanned! { span =>
>     |                                                                   ^^^^^^^^^^^^^^^^^^^ ambiguous name
>     |
>     = note: ambiguous because of a conflict between a `macro_rules` name and a non-`macro_rules` name from another module
> note: `parse_quote_spanned` could refer to the macro defined here
>    --> /Users/richard/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/pin-project-internal-0.4.28/src/utils.rs:23:1
>     |
> 23  | / macro_rules! parse_quote_spanned {
> 24  | |     ($span:expr => $($tt:tt)*) => {
> 25  | |         syn::parse2(quote::quote_spanned!($span => $($tt)*)).unwrap_or_else(|e| panic!("{}", e))
> 26  | |     };
> 27  | | }
>     | |_^
> note: `parse_quote_spanned` could also refer to the macro imported here
>    --> /Users/richard/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/pin-project-internal-0.4.28/src/pin_project/derive.rs:7:5
>     |
> 7   |     *,
>     |     ^
>     = help: use `self::parse_quote_spanned` to refer to this macro unambiguously
> 
> error[E0659]: `parse_quote_spanned` is ambiguous
>    --> /Users/richard/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/pin-project-internal-0.4.28/src/pinned_drop.rs:108:21
>     |
> 108 |             *path = parse_quote_spanned! { path.span() =>
>     |                     ^^^^^^^^^^^^^^^^^^^ ambiguous name
>     |
>     = note: ambiguous because of a conflict between a `macro_rules` name and a non-`macro_rules` name from another module
> note: `parse_quote_spanned` could refer to the macro defined here
>    --> /Users/richard/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/pin-project-internal-0.4.28/src/utils.rs:23:1
>     |
> 23  | / macro_rules! parse_quote_spanned {
> 24  | |     ($span:expr => $($tt:tt)*) => {
> 25  | |         syn::parse2(quote::quote_spanned!($span => $($tt)*)).unwrap_or_else(|e| panic!("{}", e))
> 26  | |     };
> 27  | | }
>     | |_^
> note: `parse_quote_spanned` could also refer to the macro imported here
>    --> /Users/richard/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/pin-project-internal-0.4.28/src/pinned_drop.rs:3:50
>     |
> 3   | use syn::{spanned::Spanned, visit_mut::VisitMut, *};
>     |                                                  ^
>     = help: use `self::parse_quote_spanned` to refer to this macro unambiguously
> 
> For more information about this error, try `rustc --explain E0659`.
> error: could not compile `pin-project-internal` due to 2 previous errors
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> ```

我mac系统最新版本，cpu还是m1 max的，正常跑。
建议你这样,开启vpn或者其他代理，不要用sjtu.edu
```rust
cargo clean
cargo update
cargo run
```
